// Code generated by reset generator. DO NOT EDIT.

package resetexample

func (i *Inner) Reset() {
	if i == nil {
		return
	}

	i.Value = 0
	i.Label = ""
}

func (r *ResetableStruct) Reset() {
	if r == nil {
		return
	}

	r.I = 0
	r.F = 0
	r.B = false
	r.Str = ""
	if r.StrP != nil {
		*r.StrP = ""
	}
	if r.IP != nil {
		*r.IP = 0
	}
	r.S = r.S[:0]
	clear(r.M)
	if resetter, ok := interface{}(&r.Nested).(interface{ Reset() }); ok {
		resetter.Reset()
	}
	if resetter, ok := interface{}(r.Child).(interface{ Reset() }); ok && r.Child != nil {
		resetter.Reset()
	}
	if r.SP != nil {
		*r.SP = (*r.SP)[:0]
	}
	if r.MP != nil {
		clear(*r.MP)
	}
}

func (c *Counter) Reset() {
	if c == nil {
		return
	}

	c.Count = 0
	c.Name = ""
	c.Tags = c.Tags[:0]
	clear(c.Buckets)
	c.Active = false
	c.Factor = 0
}
